[package]
name = "bitcoin-rpc-api"
version = "0.1.0"
authors = ["BCarlaYap <2826165+BCarlaYap@users.noreply.github.com>"]
edition = "2018"


[dependencies]
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
bitcoincore-rpc = "0.13.0"
bitcoincore-rpc-json = "0.13.0"
